### PR TITLE
Strip CDN from manifest output

### LINKED ISSUE #151: assets:clean / webpacker:clean task deletes the latest version of files when asset_host is set
Ruby version: 2.7.6
Rails version: 6.1.6
Webpacker version: 6.4.1

### Expected behavior:

As documented by [a comment in the implementation file itself](https://github.com/shakacode/shakapacker/blob/3ba9970e2d3addb7aae980d97c6ab4527f8e55f8/lib/webpacker/commands.rb#L8-L9), running the `webpacker:clean` task (or the enhanced `assets:clean` task) should _**always**_ keep the latest version of compiled assets as indicated by _manifest.json_.

There is no expectation that setting `config.asset_host` (or the longer name of `config.action_controller.asset_host`) in _production.rb_ should change this behaviour.

### Actual behavior:

If a host is set for `config.asset_host`, then the `webpacker:clean` task will sometimes remove even the latest version of assets, leading to 404s for those assets. I think this is down to the age of the asset file.

### Steps to reproduce:

1. Set `config.asset_host` to any host in _production.rb_, eg `config.asset_host = example.com`
2. Run `RAILS_ENV=production bundle exec rails assets:precompile`
3. Wait 1 second
4. Run RAILS_ENV=production bundle exec rake webpacker:clean[2,1]
5. See that all your new assets just got removed!

(To save you from looking, the '1' argument in the command sets the maximum age of assets that are no longer considered the "latest" version to 1 second.)

### Cause:

Setting `config.asset_host` causes full URLs to be inserted into the _manifest.json_, eg:
```js
{
  // ... other assets ...
  "application.js": "//example.com/packs/js/application-50abb05db229c31c1e24.js",
  // ... other assets ...
}
```
which is already [documented in the troubleshooting docs](https://github.com/shakacode/shakapacker/blob/3ba9970e2d3addb7aae980d97c6ab4527f8e55f8/docs/troubleshooting.md#wrong-cdn-src-from-javascript_pack_tag) relating to another issue.

I couldn't locate the PR/motivation for this change to _manifest.json_, but as a reminder, prior to shakapacker/webpacker v6 manifest.json did not include the asset_host.

Unfortunately the implementation of `webpacker:clean` was not updated to handle this, so it is expecting to get local file paths but getting remote URLs from _manifest.json_. Since none of the local assets paths match the remote URLs, this in turns means that no local assets are kept due to being the current version, and they are only ever kept if they meet the criteria for keeping a backup.
https://github.com/shakacode/shakapacker/blob/3ba9970e2d3addb7aae980d97c6ab4527f8e55f8/lib/webpacker/commands.rb#L69-L78

In particular, on line 74 `value` is a URL so sticking this on the end of the project root path produces a half-local-path half-URL string.

### Workaround:

Like the linked troubleshooting issue, setting the `WEBPACKER_ASSET_HOST` env variable to an empty string causes the _manifest.json_ to revert to having relative paths, so the `webpacker:clean` task then works correctly.

### Thoughts on priority:

This is quite a nasty issue as things might work absolutely fine when initially upgrading to shakapacker, but then start failing in weird ways on subsequent builds.

You can get very strange behaviours since all of the logic is based off of the file age, so in my case running `assets:clean` removed a `foo.js` file while leaving the equivalent `foo.js.gz` file intact, causing much head scratching due things working in some browsers and not others.

### PR DESCRIPTION
**Pull request by tomdracz**
### Summary
Fixes #151 

Asset manifests path used to be output without CDN as per https://github.com/rails/webpacker/pull/1974

But then aborted Webpacker v6 added the CDN back for reasons unknown https://github.com/rails/webpacker/pull/2802

This is causing issues with the clean tasks and requires other workarounds as outlined in https://github.com/shakacode/shakapacker/blob/main/docs/troubleshooting.md#wrong-cdn-src-from-javascript_pack_tag

The PR reverts this behaviour so the assets are once again listed in the manifest output without CDN

### Pull Request checklist

- [x] Add/update test to cover these changes
- [x] Update CHANGELOG file

## Summary by CodeRabbit

- **Bug Fixes**
  - Reverted CDN URL changes in asset paths to restore previous Webpacker behavior.

- **Documentation**
  - Updated upgrade guide to v8, highlighting changes in CDN host inclusion and its impact on asset referencing and compilation.

- **Tests**
  - Added a test to ensure the public path without a CDN is not influenced by the asset host configuration.

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]

File: package/environments/base.js [hunk 1]
```diff
@@ -80,7 +80,7 @@ const getPlugins = () => {
       writeToDisk: true,
       output: config.manifestPath,
       entrypointsUseAssets: true,
-      publicPath: true
+      publicPath: config.publicPathWithoutCDN
```
Comment (justin808) [inline package/environments/base.js:83]: We need to document who this affects and the migration instructions.

Comment (tomdracz) [reply package/environments/base.js:83]: Cool, I'll get something added to the migration guide

Comment (justin808) [reply package/environments/base.js:83]: Done?

File: docs/v8_upgrade.md [hunk 2]
```diff
@@ -7,6 +7,34 @@ manager is used to manage JavaScript dependencies.
...
+
+To get around that, you can use dynamic override as outlined by [Webpack documentation](https://webpack.js.org/guides/asset-modules/#on-the-fly-override).
+
+Setting for example:
+
+```
+__webpack_public_path__ = 'https://mycdn.url.com/packs';
+```
+
+In your code and ensuring it is run first in the app, will allow the dynamic imports lookup path to be overriden at runtime.
```
Comment (justin808) [inline docs/v8_upgrade.md:36]: Overall, the setting of an assets CDN during compilation is maybe a huge anti-pattern as it precludes using the same bundles on staging and production unless your assets are exactly the same and properly fingerprinted. 

Thoughts? Should this be mentioned?

In other words, shouldn't the CDN be set via an ENV value and not put into the builds?

Comment (tomdracz) [reply docs/v8_upgrade.md:36]: > Overall, the setting of an assets CDN during compilation is maybe a huge anti-pattern as it precludes using the same bundles on staging and production unless your assets are exactly the same and properly fingerprinted.

It's kinda what Webpack does though and usually mentions in their docs when CDN comes into play https://webpack.js.org/guides/public-path/#environment-based

> In other words, shouldn't the CDN be set via an ENV value and not put into the builds?

`__webpack_public_path__` will let you do something like that but there's extra steps involved - how do you pass that ENV value to the build output?

You could probably do something like `__webpack_public_path__ = window.publicPathOverride` but then ensure that this is executed and available in your app view code

File: docs/v8_upgrade.md [hunk 3]
```diff
@@ -7,6 +7,52 @@ manager is used to manage JavaScript dependencies.
...
+  output: {
+    publicPath: 'auto'
+  }
+};
+
+module.exports = generateWebpackConfig(customConfig);
+```
+
+This will work in number of environments although some older browsers like IE will require a polyfill as mentioned in the Webpack documentation linked above.
+
```
Comment (tomdracz) [inline docs/v8_upgrade.md:55]: Documented usage of `auto` publicPath that should be a happy-medium for the CDN assets. With this option and `config.asset_host` specified I see all imports coming from that host defined @justin808 

Might consider making this a default or opt-in behaviour but would need to dig further to understand consequences of that
