### PR TITLE
fix: `hmr: false` doesn't disable Hot Module Replacement

### LINKED ISSUE #390: `hmr: false` does not disable Hot Module Replacement
Starting with version 4, webpack-dev-server defaults to Hot Module Replacement enabled:
https://github.com/webpack/webpack-dev-server/blob/540c43852ea33f9cb18820e1cef05d5ddb86cc3e/CHANGELOG.md?plain=1#L561
https://github.com/webpack/webpack-dev-server/blob/540c43852ea33f9cb18820e1cef05d5ddb86cc3e/lib/Server.js#L1081

Shakapacker assumes the default is disabled: If `hmr: true` the `--hot` flag [gets added](https://github.com/shakacode/shakapacker/blob/0b0e1c71a8c3e087d47efb5c5aea960842a179da/lib/shakapacker/dev_server_runner.rb#L89) to the webpack-dev-server command, but `hmr: false` does nothing. To actually disable HMR you must add `hot: false` to shakapacker.yml or the `--no-hot` command line flag.

### PR DESCRIPTION
**Pull request by thedanbob**
### Summary

webpacker-dev-server >= 4 enables HMR by default, so explicitly disable when `hmr: false`. Fixes #390

### Pull Request checklist

- [x] Add/update test to cover these changes
- [x] ~Update documentation~
- [x] Update CHANGELOG file

### CODE REVIEW

File: lib/shakapacker/dev_server_runner.rb [hunk 1]
```diff
@@ -86,8 +86,12 @@ def execute_cmd
...
         cmd += ["--progress", "--color"] if @pretty
 
-        cmd += ["--hot"] if @hot
-        cmd += ["only"] if @hot == "only"
+        if @hot
+          cmd += ["--hot"]
+          cmd += ["only"] if @hot == "only"
+        else
+          cmd += ["--no-hot"]
+        end
```
Comment (ahangarha) [inline lib/shakapacker/dev_server_runner.rb:94]: Since `webpack` enables `hmr` by default, we don't need to pass explicitly `--hot`. So I think we can simplify the logic, drop the `--hot` addition, and only add `only` or `--no-hot` as per the value of `@hot`. Something like

```rb
# We don't add `--hot` of `@hot == true` since it is the default behavior of webpack.
cmd << "--no-hot" unless @hot
cmd << "only" if @hot == "only"
```

I think adding the comment is good for providing context.

File: spec/backward_compatibility_specs/dev_server_runner_spec.rb [hunk 2]
```diff
@@ -26,27 +26,27 @@
...
       it "runs the command using the manager" do
-        cmd = package_json.manager.native_exec_command("webpack", ["serve", "--config", "#{test_app_path}/config/webpack/webpack.config.js"])
+        cmd = package_json.manager.native_exec_command("webpack", ["serve", "--config", "#{test_app_path}/config/webpack/webpack.config.js", "--no-hot"])
 
         verify_command(cmd)
       end
 
       it "passes on arguments" do
-        cmd = package_json.manager.native_exec_command("webpack", ["serve", "--config", "#{test_app_path}/config/webpack/webpack.config.js", "--quiet"])
+        cmd = package_json.manager.native_exec_command("webpack", ["serve", "--config", "#{test_app_path}/config/webpack/webpack.config.js", "--no-hot", "--quiet"])
```
Comment (ahangarha) [inline spec/backward_compatibility_specs/dev_server_runner_spec.rb:43]: I wonder if we should change the configuration file and set `hmr: true`. It helps to keep the tests cleaner and more focused. It is weird to have `--no-hot` on so many tests.

@justin808 What do you think?

Also, I can think of it as a separate PR.

**Review by ahangarha — CHANGES_REQUESTED** [review]
Thanks for the PR. I just made some suggestions. What do you think about them?

File: lib/shakapacker/dev_server_runner.rb (hunk 1 above)
Comment (thedanbob) [reply lib/shakapacker/dev_server_runner.rb]: Makes sense, I've made this change in a slightly different way.

**Comment by justin808** [comment]
@thedanbob can I get a link to the docs or source code of the '--no-hot' option?

**Comment by ahangarha** [comment]
@justin808 
In the readme of the `webpack-dev-server`, [it is mentioned](https://github.com/webpack/webpack-dev-server/blob/540c43852ea33f9cb18820e1cef05d5ddb86cc3e/README.md?plain=1#L133).

 Apart from that, all of the options in webpack CLI can be reverted by using `no` prefix. This is why no explicit reference or implementation of `--no-hot` exists in the code base. `--no-hot` is simply the opposite of `--hot`, so it sets `hot` to false.

**Comment by thedanbob** [comment]
@justin808 I just checked and this would work as well, and is perhaps cleaner:
```ruby
cmd += ["--hot", (@hot || false).to_s] if @hot != true
```

Of course I'll have to adjust the tests to match. Probably making the default (in the tests) as `hmr: true` would be best, as @ahangarha suggested.

**Comment by ahangarha** [comment]
@thedanbob 
> `cmd += ["--hot", (@hot || false).to_s] if @hot != true`

I prefer a more visible code in more lines over one-liners. It is simpler to read, understand, and debug.

**Comment by thedanbob** [comment]
How does this look? I went ahead and changed the tests to use `hmr: true`. My implementation did have a side effect on a couple of `inlining_css` tests but I think the behavior change is unimportant?

File: lib/shakapacker/dev_server_runner.rb [hunk 3]
```diff
@@ -86,8 +86,8 @@ def execute_cmd
         cmd += ["--config", @webpack_config]
         cmd += ["--progress", "--color"] if @pretty
 
-        cmd += ["--hot"] if @hot
-        cmd += ["only"] if @hot == "only"
+        # Default behavior of webpack-dev-server is @hot = true
+        cmd += ["--hot", @hot.to_s] if @hot != true
```
Comment (ahangarha) [inline lib/shakapacker/dev_server_runner.rb:90]: If `@hot` is `false`, `cmd` becomes `[..., "--hot", "false",...]` which is wrong. It is also wrong with `nil` value because it adds `""` to the list. Some commands are sensitive about getting blank options.


I would propose using typical `if` conditions for explicit values (`true`, `false, `only`).

**Review by ahangarha — CHANGES_REQUESTED** [review]
Thanks for the updates. I Shared my concerns in the comments.

File: lib/shakapacker/dev_server_runner.rb [hunk 4]
```diff
@@ -30,7 +30,7 @@ def load_config
         @port              = dev_server.port
         @pretty            = dev_server.pretty?
         @https             = dev_server.protocol == "https"
-        @hot               = dev_server.hmr?
+        @hot               = dev_server.hmr? || false
```
[the remark this answers is not in the document]
Comment (thedanbob) [reply lib/shakapacker/dev_server_runner.rb:33]: This was to accommodate the logic below

File: lib/shakapacker/dev_server_runner.rb (hunk 3 above)
Comment (thedanbob) [reply lib/shakapacker/dev_server_runner.rb:90]: `--hot false` actually does work according to my testing, but perhaps it's not guaranteed to work in the future. Adding a default value of `false` above was to ensure `@hot` wouldn't be nil here. But I'll change it back to use `--no-hot`.

**Review by ahangarha — APPROVED** [review]
Looks good to me.
Thanks.

**Comment by justin808** [comment]
Thanks @thedanbob!
