### PR TITLE
Remove unneeded code related to CSP config 

### LINKED ISSUE #221: Warning of rails  webpacker:install for failing to update CSP file on Rails 7+
Ruby version: 3.1.2
Rails version: 7.0.1
Shakapacker version: 6.5.4

## Expected behavior:
Installation goes smooth

## Actual behavior:
Running `rails webpacker:install` on Rails 7, produces the following lines:

```
...
Make note of webpack-dev-server exemption needed to csp
File unchanged! The supplied flag value not found!  config/initializers/content_security_policy.rb
...
```

## Small, reproducible repo:
Doesn't need any specific setup.

## Insight
This happens because the generator fail in finding the specific lines in the `content_security_policy.rb` file. That is because the format of this file has changes in Rails 7. But also it seems it is not needed anymore since the app works fine without updating this file.

So a possible proposal would be to modify this file only if the Rails version is below 7.

### PR DESCRIPTION
**Pull request by ahangarha**
Since CSP file (`config/content_security_policy.rb`) format has changed in Rails 7, shakapacker generator on `webpacker:install` causes a warning mentioned in #221. Also it seems we don't need to modify this file in Rails 7.

closes #221

Warning: Since we don't cover Rails 7 in our CI, this PR doesn't have proper test.

### CODE REVIEW

**Comment by justin808** [comment]
How do you know if this only affects for rails 7 and and not earlier?

**Comment by ahangarha** [comment]
@justin808 
Thanks for mentioning this.
For this we need to have a generator test that both test where it should and shouldn't have impact.
So actually we have no test for this except testing manually. (which I did, and found/fix the bug in the proposed change)

File: lib/install/template.rb [hunk 1]
```diff
@@ -45,7 +45,7 @@
 RUBY
 end
 
-if (csp_config_path = Rails.root.join("config/initializers/content_security_policy.rb")).exist?
+if Rails::VERSION::MAJOR < 7 && (csp_config_path = Rails.root.join("config/initializers/content_security_policy.rb")).exist?
```
Comment (justin808) [inline lib/install/template.rb:48]: Why is this only Rails 7? Do you have a doc link?

Comment (justin808) [reply lib/install/template.rb:48]: https://github.com/shakacode/shakapacker/blame/40a5803b5963c74c733109f5c852cacc619289f6/lib/install/template.rb#L81-L86

Probably just delete all these lines.

Why? Newer versions of Webpacker (for many years) proxy to the webpack dev server, so maybe no need for the browser to know about any other server. However, I'm not 100% sure if WebSockets connections from HMR need or don't need this addition. In other words, the browser will still try to go to port 3035 and that might need the CSP rule. And if so, then we should not turn this off. **If so, we need to fix the root cause and fix the generator for Rails 7**

Please remove the lines and check if Rails 6 HMR works with them gone. And try Rails 7.

I'm not so worried about Rails 5. Nobody is going to run the generator on Rails 5.

This commit added the proxy.
https://github.com/shakacode/shakapacker/commit/68b9f086c1d262be895c2750cb3a25879157733a

This the code that seems unnecessary:

```rb
if Rails::VERSION::MAJOR == 5 && Rails::VERSION::MINOR > 1
  say "You need to allow webpack-dev-server host as allowed origin for connect-src.", :yellow
  say "This can be done in Rails 5.2+ for development environment in the CSP initializer", :yellow
  say "config/initializers/content_security_policy.rb with a snippet like this:", :yellow
  say "policy.connect_src :self, :https, \"http://localhost:3035\", \"ws://localhost:3035\" if Rails.env.development?", :yellow
end
```

Comment (ahangarha) [reply lib/install/template.rb:48]: You were absolutely right. I just tested a basic setup with Rails 5, 6, and 7 and in all of them, without modifying CSP config, HMR worked perfectly. So I am going to update this PR.

And thanks for your hints on why this is no longer needed.

**Review by Judahmeek — APPROVED** [review]
