### PR TITLE
Fix bin/setup modification failure in installation

### LINKED ISSUE #226: Fail in updating `bin/setup`
Ruby version: 2.7.5
Rails version: 5.2.8 & 6.1.7
Shakapacker version: 6.5.4

## Expected behavior:
The generator (`rails webpacker:install`) is supposed to update `bin/setup` file.

## Actual behavior:
The generator produces the following warning:

```
File unchanged! The supplied flag value not found!  bin/setup
```

## Cause
Generator (at [this line](https://github.com/shakacode/shakapacker/blob/master/lib/install/template.rb#L41)) cannot find the relevant line in `bin/setup` since it uses double quote. As a result, this the relevant line can be found in Rails 7 but not in Rails 5 or 6.

### PR DESCRIPTION
**Pull request by ahangarha**
Due to different content of `bin/setup` in different Rails versions, the earlier version of the generator couldn't modify this file properly in all circumstances.

This commit handles the following scenarios:
- If there is a commented line for `system('bin/yarn')`, uncomment it.
- Otherwise, regardless of using single or double quotations in different Rails versions, add `system! 'bin/yarn'` after the intended line.

I have manually checked the impact of this PR on the following Rails versions:
- `5.2.8`: where we already have commented `system('bin/yarn')`
- `6.1.7`: where we have `system('bundle check') || system!('bundle install')`
- `7.0.4`: where we have `system("bundle check") || system!("bundle install")`

closes #226

### CODE REVIEW

File: lib/install/template.rb [hunk 1]
```diff
@@ -38,11 +38,27 @@
 
 if (setup_path = Rails.root.join("bin/setup")).exist?
   say "Run bin/yarn during bin/setup"
-  insert_into_file setup_path.to_s, <<-RUBY, after: %(  system("bundle check") || system!("bundle install")\n)
+
+  if File.read(setup_path).match? Regexp.escape("  # system('bin/yarn')\n")
+    gsub_file setup_path, "# system('bin/yarn')", 'system! "bin/yarn"'
```
Comment (Judahmeek) [inline lib/install/template.rb:43]: @justin808 prefers that we use parentheses `()` whenever possible with ruby methods

Example: `gsub_file(setup_path, "# system('bin/yarn')", 'system! "bin/yarn"')`

File: lib/install/template.rb [hunk 2]
```diff
@@ -38,11 +38,27 @@
...
+  else
+    # Due to the inconsistency of quotation usage in Rails 7 compared to
+    # earlier versions, we check both single and double quotations here.
+    pattern = /system\(['"]bundle check['"]\) \|\| system!\(['"]bundle install['"]\)\n/
+
+    if File.read(setup_path).match? pattern
+      insert_into_file setup_path.to_s, <<-RUBY, after: pattern
```
Comment (Judahmeek) [inline lib/install/template.rb:50]: please add parentheses

**Review by Judahmeek — CHANGES_REQUESTED** [review]

File: lib/install/template.rb (hunk 1 above)
Comment (ahangarha) [reply lib/install/template.rb:43]: Thanks for mentioning this. I also prefer to add parentheses. In some cases, I just try to follow the surrounding code convention.

If using parentheses is what we all prefer, then it is good. Will do this now onward.

Comment (ahangarha) [reply lib/install/template.rb:43]: @Judahmeek 
Should I add parentheses to all other methods in the file (in order to keep consistency)? If not, do we have any rule on where to add parentheses and where to not (given that functionally there be no difference)?

File: lib/install/template.rb (hunk 2 above)
Comment (ahangarha) [reply lib/install/template.rb]: @Judahmeek Done but only on the code I added.

File: lib/install/template.rb [hunk 3]
```diff
@@ -38,11 +38,27 @@
...
-  system! "bin/yarn"
+  system!("bin/yarn")
 RUBY
+    else
+      say <<~MSG, :red
+        It seems your `bin/setup` file doesn't have the expected content.
+        Please review the file and manually add `system! "bin/yarn"`.
+      MSG
+    end
+  end
```
Comment (ahangarha) [inline lib/install/template.rb:61]: @Judahmeek @justin808 
What about adding these lines at the end of the file if we couldn't find the pattern? The job of this step in the generator is to ensure we have `system!("bin/yarn")` in the `setup` file. So why should we ask the user to do it manually?

I think it would be good to print out some text and say thought we have updated the `setup` file, but the format of the file was not what we expected. This way, we can ask the developer to review the content of this file and ensure everything is right in the file.

It is not a very important thing to be worried about but I think if we are updating this part, we do it in the right way. Is my proposal the right way? What do you think?

**Comment by justin808** [comment]
@ahangarha I'll merge after you update the CHANGELOG.

However, I'm not convinced this modification regarding bin/yarn is even needed longer term.

**Comment by ahangarha** [comment]
> @ahangarha I'll merge after you update the CHANGELOG.
> 
> However, I'm not convinced this modification regarding bin/yarn is even needed longer term.

@justin808 I updated the changelog.
If we don't need such modification at all, then we should remove it entirely.
I think it would be good to make a final decision about this matter before our next major release.

File: lib/install/template.rb [hunk 4]
```diff
@@ -38,11 +38,27 @@
 
 if (setup_path = Rails.root.join("bin/setup")).exist?
   say "Run bin/yarn during bin/setup"
-  insert_into_file setup_path.to_s, <<-RUBY, after: %(  system("bundle check") || system!("bundle install")\n)
+
+  if File.read(setup_path).match? Regexp.escape("  # system('bin/yarn')\n")
```
Comment (vaukalak) [inline lib/install/template.rb:42]: @ahangarha 

[] please extract `system('bin/yarn')` to a const, also why it's `system('bin/yarn')` and `system**!**('bin/yarn')` in other places?
[] please add a warn, that the file has been modified.
[] (optional), add a comment what and why we are uncommenting, unless this will not be intuitive from the log above.

File: lib/install/template.rb [hunk 5]
```diff
@@ -38,11 +38,27 @@
...
+    if File.read(setup_path).match? pattern
+      insert_into_file(setup_path.to_s, <<-RUBY, after: pattern)
 
   # Install JavaScript dependencies
-  system! "bin/yarn"
+  system!("bin/yarn")
 RUBY
+    else
+      say <<~MSG, :red
+        It seems your `bin/setup` file doesn't have the expected content.
```
Comment (vaukalak) [inline lib/install/template.rb:57]: Do we have a section in the docs, which might be referenced in this warn message?

**Review by vaukalak — CHANGES_REQUESTED** [review]
please give feedback to the comments above.

File: lib/install/template.rb (hunk 5 above)
Comment (ahangarha) [reply lib/install/template.rb:57]: I don't think so. But also see my comment [here](https://github.com/shakacode/shakapacker/pull/229#discussion_r1064466091):

> What about adding these lines at the end of the file if we couldn't find the pattern? The job of this step in the generator is to ensure we have `system!("bin/yarn")` in the `setup` file. So why should we ask the user to do it manually?

I didn't get any response on it. Do you have any?

File: lib/install/template.rb (hunk 4 above)
Comment (vaukalak) [reply lib/install/template.rb:42]:
```
Regarding system and system!, rails 5 used system only. I didn't check if it was intended. Since we use ! for it, it is uncommented and changed to system!. Do you think there was a particular reason behind using system in Rails 5?
```
@ahangarha thanks, this makes sense. Could you please then just some comments, or extract a function, so the code will be easier to understand?

File: lib/install/template.rb (hunk 5 above)
Comment (vaukalak) [reply lib/install/template.rb:57]: @ahangarha I think it's a good idea to add both in this case and keep the message, which will give heads-up to the user.

**Review by vaukalak — APPROVED** [review]
